name: Deploy Flask Static Files to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write
  pages: write

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Flask

      - name: Verify Script
        run: ls -l generate_static_files.py

      - name: Generate Static Files
        run: |
          python generate_static_files.py
          mv ./static ./output

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          path: ./output
