name: Deploy Flask App with CI/CD

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests (Optional)
        run: pytest  # Replace with your test framework

      - name: Deploy to Production
        env:
          FLASK_APP: app.py
          FLASK_ENV: production
        run: |
          # Start Flask server using Gunicorn (Replace command as needed)
          gunicorn --bind 0.0.0.0:5000 app:app
